*** Comments ***
Deverlop By: Pakorn Soikham
Date: 25-01-2025


*** Variables ***
${CONTENT_LOGIN_PAGE}               เข้าสู่ระบบ

${LOCATER_BTN_LOGIN_PAGE}           xpath=//a[@class='btn-allmember-login nopd onLine']
${LOCATOR_USERNAME}                 name=email
${LOCATOR_PASSWORD}                 name=password
${LOCATOR_BTN_LOGIN}                css=a.btn.btn-small
${LOCATOR_BTN_SKIP_ALL_MEMBER}      css=button.btn.btn-orange
